export const initialdata = [
  {
    id: 1,
    title: "Cozy Downtown Loft",
    price: "$500/month",
    location: "Downtown",
    city: "Addis Ababa",
    size: "1 bedroom",
    image: "/house1.jpg",
  },
  {
    id: 2,
    title: "Modern Lakeside Villa",
    price: "$680/month",
    location: "Lakeside",
    city: "Bahir Dar",
    size: "2 bedrooms",
    image: "/house3.jpg",
  },
  {
    id: 3,
    title: "Spacious Suburban Home",
    price: "$860/month",
    location: "Suburbs",
    city: "Hawassa",
    size: "3+ bedrooms",
    image: "/house2.jpg",
  },
  {
    id: 4,
    title: "Charming Central Flat",
    price: "$1040/month",
    location: "Central",
    city: "Adama",
    size: "1 bedroom",
    image: "/house4.jpg",
  },
  {
    id: 5,
    title: "Sunny Hillside Retreat",
    price: "$1220/month",
    location: "Hillside",
    city: "Addis Ababa",
    size: "2 bedrooms",
    image: "/house1.jpg",
  },
  {
    id: 6,
    title: "Luxury Lake House",
    price: "$1400/month",
    location: "Lakeside",
    city: "Bahir Dar",
    size: "3+ bedrooms",
    image: "/house2.jpg",
  },
  {
    id: 7,
    title: "Quiet Suburban Nest",
    price: "$1580/month",
    location: "Suburbs",
    city: "Hawassa",
    size: "1 bedroom",
    image: "/house3.jpg",
  },
  {
    id: 8,
    title: "Urban Central Condo",
    price: "$1760/month",
    location: "Central",
    city: "Adama",
    size: "2 bedrooms",
    image: "/house4.jpg",
  },
  {
    id: 9,
    title: "Stylish Downtown Pad",
    price: "$1940/month",
    location: "Downtown",
    city: "Addis Ababa",
    size: "1 bedroom",
    image: "/house1.jpg",
  },
  {
    id: 10,
    title: "Rustic Villa Escape",
    price: "$2120/month",
    location: "Lakeside",
    city: "Bahir Dar",
    size: "3+ bedrooms",
    image: "/house2.jpg",
  },
  {
    id: 11,
    title: "Family Suburban Getaway",
    price: "$2300/month",
    location: "Suburbs",
    city: "Hawassa",
    size: "2 bedrooms",
    image: "/house3.jpg",
  },
  {
    id: 12,
    title: "Sleek Central Studio",
    price: "$2480/month",
    location: "Central",
    city: "Adama",
    size: "1 bedroom",
    image: "/house4.jpg",
  },
  {
    id: 13,
    title: "Bright City Apartment",
    price: "$2660/month",
    location: "Downtown",
    city: "Addis Ababa",
    size: "2 bedrooms",
    image: "/house1.jpg",
  },
  {
    id: 14,
    title: "Elegant Lake Retreat",
    price: "$2840/month",
    location: "Lakeside",
    city: "Bahir Dar",
    size: "3+ bedrooms",
    image: "/house2.jpg",
  },
  {
    id: 15,
    title: "Cozy Suburban Flat",
    price: "$3020/month",
    location: "Suburbs",
    city: "Hawassa",
    size: "1 bedroom",
    image: "/house3.jpg",
  },
  {
    id: 16,
    title: "Modern Central Loft",
    price: "$3200/month",
    location: "Central",
    city: "Adama",
    size: "2 bedrooms",
    image: "/house4.jpg",
  },
  {
    id: 17,
    title: "Downtown Studio Haven",
    price: "$3380/month",
    location: "Downtown",
    city: "Addis Ababa",
    size: "1 bedroom",
    image: "/house1.jpg",
  },
  {
    id: 18,
    title: "Grand Villa Oasis",
    price: "$3560/month",
    location: "Lakeside",
    city: "Bahir Dar",
    size: "3+ bedrooms",
    image: "/house2.jpg",
  },
  {
    id: 19,
    title: "Spacious Rural House",
    price: "$3740/month",
    location: "Suburbs",
    city: "Hawassa",
    size: "2 bedrooms",
    image: "/house3.jpg",
  },
  {
    id: 20,
    title: "Chic Urban Retreat",
    price: "$3920/month",
    location: "Central",
    city: "Adama",
    size: "1 bedroom",
    image: "/house4.jpg",
  },
  {
    id: 21,
    title: "Vibrant Downtown Condo",
    price: "$4100/month",
    location: "Downtown",
    city: "Addis Ababa",
    size: "2 bedrooms",
    image: "/house1.jpg",
  },
  {
    id: 22,
    title: "Serene Lakeside Villa",
    price: "$4280/month",
    location: "Lakeside",
    city: "Bahir Dar",
    size: "3+ bedrooms",
    image: "/house2.jpg",
  },
  {
    id: 23,
    title: "Suburban Family Home",
    price: "$4460/month",
    location: "Suburbs",
    city: "Hawassa",
    size: "2 bedrooms",
    image: "/house3.jpg",
  },
  {
    id: 24,
    title: "Minimalist Central Flat",
    price: "$4640/month",
    location: "Central",
    city: "Adama",
    size: "1 bedroom",
    image: "/house4.jpg",
  },
  {
    id: 25,
    title: "Trendy Urban Loft",
    price: "$5000/month",
    location: "Downtown",
    city: "Addis Ababa",
    size: "2 bedrooms",
    image: "/house1.jpg",
  },
];
